fails:Kernel.at_exit is a private method
fails:Kernel.at_exit gives access to the last raised exception
